### ISSUE TITLE
Question: Could you explain how data file to updated.

### ISSUE THREAD

**Issue by jskframily** [T3AS/DeepOrder-ICSME21#1]
In dataset files, there are two categories raw data and updated.
for example, gsdtsr.csv and gsdtsr_updated.csv.

My question is how do you make _update.csv file?

**Comment by AizazSharif** [comment]
Hi,
In the repository, I have already provided **ROCKET_on_Cisco.ipynb** for conversion of the dataset to DeepOrder requirements. 

Now you can also find the jupyter files such as **converting_gsdtsr.csv_to_DeepOrder_dataset_format.ipynb** that I just added for the remaining datasets.
