### ISSUE TITLE
Tensorflow version

### ISSUE THREAD

**Issue by laurabrzmeyer** [T3AS/DeepOrder-ICSME21#2]
Hello,
I'm using python 3.6 and the following requirements:
> importlib-metadata==1.7.0
> tensorflow==2.1.0
> numpy
> matplotlib
> seaborn
> pandas
> Keras==2.2.4
> SMOGN
> scikit-learn

However, I'm getting an error on tensorflow's function get_default_graph.
The requirements above are all correct? 
The error is: 
> AttributeError: module 'tensorflow' has no attribute 'get_default_graph'

I've already modified two lines to fix other AttributErrors:

> #config = tf.ConfigProto()
> config = tf.compat.v1.ConfigProto()
> #session = tf.Session(config=config)
> session = tf.compat.v1.Session(config=config)

Thanks,
Laura.

**Comment by AizazSharif** [comment]
Hi,

Sorry for the delayed response. The TensorFlow and other versions mentioned are correct but I have also noticed TensorFlow not directly working on old projects.
Maybe you can try the following solutions proposed in the following links:

https://github.com/keras-team/keras/issues/12379
https://stackoverflow.com/questions/55496289/how-to-fix-attributeerror-module-tensorflow-has-no-attribute-get-default-gr

**Comment by AizazSharif** [comment]
Also @laurabrzmeyer 

I realized you mentioned that you are using Python 3.6 which might be a problem. Try changing it to 3.7.

**Comment by laurabrzmeyer** [comment]
Hello @AizazSharif,
Thanks for your response!
I've resolved the issue using the following requirements:
      importlib-metadata==1.7.0
      tensorflow==2.1.0
      numpy
      matplotlib
      seaborn
      pandas
      Keras==2.3.1
      SMOGN
      scikit-learn
And then I called the functions ConfigProto and Session as follows:
    config = tf.compat.v1.ConfigProto()
    session = tf.compat.v1.Session(graph=tf.compat.v1.get_default_graph(), config=config)

**Comment by AizazSharif** [comment]
That is great then. I will re-run the files and update the requirements.txt if needed.
