### ISSUE TITLE
Some question about dataset

### ISSUE THREAD

**Issue by now4fun** [T3AS/DeepOrder-ICSME21#3]
Hello, I have some questions about the dataset that I hope you can help me with:
Question 1: When preparing my test case dataset, I would like to know what file format I should use and which columns are necessary. Also, I am unsure about the format of the original dataset, especially regarding the _update files in the Datasets directory.
Question 2: In the dataset, how is CI iteration represented? Do E1/E2/E3 represent three different iterations? Additionally, what does the "Cycle" field signify? This has left me confused. If E1/E2/E3 do indeed represent iterations, then the "name" column should be unique, but I see duplicate values in the dataset.
I look forward to your answers and guidance. Thank you for your time and assistance!

**Comment by AizazSharif** [comment]
Hi @now4fun,

Answer 1: You can use CSV file format as used by DeepOrder (both for original and updated datasets). As for the columns, as mentioned in the paper we are using 14 columns/features which are obtained after the feature extraction process. The features can be extracted using jupyter notebooks and the final set of important columns can be seen in same notebooks as well as in the [dataset](https://drive.google.com/drive/folders/1f69PUA__pvs_k4bmszIUtQ8buCZg_QAo).


Answer 2:  CI iteration is represented as cycle. We are comparing results with a minimum of 4 cycles versus >4 cycles. 
'E1/E2/E3' are the last three execution statuses of tests in each cycle.
'cycle' is to group the test cases to the respective CI cycles. 
'name' column acts as a unique id for each test case. If it is duplicate, it shows that they are run more than one times.


I hope I have answered your questions.
